/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.dialogos;

import com.personal.utiles.FormularioUtil;
import entidades.DetalleJornada;
import java.util.Date;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RyuujiMD
 */
public class DlgDetalleJornada extends javax.swing.JDialog {

    /**
     * Creates new form DlgDetalleJornada
     */
    private DetalleJornada detalleJornada;
//    private List<DetalleJornada> detalleJornadList;
    public DlgDetalleJornada(JInternalFrame parent, boolean modal) {
        super(JOptionPane.getFrameForComponent(parent), modal);
        initComponents();
        inicializar();
        this.setLocationRelativeTo(parent);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlEntrada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spEntrada = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spEntradaTolerancia = new javax.swing.JSpinner();
        pnlEntradaMarcacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spEntradaDesde = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spEntradaHasta = new javax.swing.JSpinner();
        pnlEntrada1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        spSalida = new javax.swing.JSpinner();
        pnlEntradaMarcacion1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        spSalidaDesde = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        spSalidaHasta = new javax.swing.JSpinner();
        chkDiaSiguiente = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Defina los parámetros de jornada");

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        pnlEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));
        java.awt.GridBagLayout pnlEntradaLayout = new java.awt.GridBagLayout();
        pnlEntradaLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlEntradaLayout.rowHeights = new int[] {0, 5, 0};
        pnlEntrada.setLayout(pnlEntradaLayout);

        jLabel1.setText("Hora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada.add(jLabel1, gridBagConstraints);

        spEntrada.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada.add(spEntrada, gridBagConstraints);

        jLabel2.setText("Tolerancia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada.add(jLabel2, gridBagConstraints);

        spEntradaTolerancia.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlEntrada.add(spEntradaTolerancia, gridBagConstraints);

        pnlEntradaMarcacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcación"));
        java.awt.GridBagLayout pnlEntradaMarcacionLayout = new java.awt.GridBagLayout();
        pnlEntradaMarcacionLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlEntradaMarcacionLayout.rowHeights = new int[] {0};
        pnlEntradaMarcacion.setLayout(pnlEntradaMarcacionLayout);

        jLabel3.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion.add(jLabel3, gridBagConstraints);

        spEntradaDesde.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion.add(spEntradaDesde, gridBagConstraints);

        jLabel4.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion.add(jLabel4, gridBagConstraints);

        spEntradaHasta.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion.add(spEntradaHasta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada.add(pnlEntradaMarcacion, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(pnlEntrada, gridBagConstraints);

        pnlEntrada1.setBorder(javax.swing.BorderFactory.createTitledBorder("Salida"));
        java.awt.GridBagLayout pnlEntrada1Layout = new java.awt.GridBagLayout();
        pnlEntrada1Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        pnlEntrada1Layout.rowHeights = new int[] {0, 5, 0};
        pnlEntrada1.setLayout(pnlEntrada1Layout);

        jLabel5.setText("Hora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada1.add(jLabel5, gridBagConstraints);

        spSalida.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada1.add(spSalida, gridBagConstraints);

        pnlEntradaMarcacion1.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcación"));
        java.awt.GridBagLayout pnlEntradaMarcacion1Layout = new java.awt.GridBagLayout();
        pnlEntradaMarcacion1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlEntradaMarcacion1Layout.rowHeights = new int[] {0};
        pnlEntradaMarcacion1.setLayout(pnlEntradaMarcacion1Layout);

        jLabel7.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion1.add(jLabel7, gridBagConstraints);

        spSalidaDesde.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion1.add(spSalidaDesde, gridBagConstraints);

        jLabel8.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion1.add(jLabel8, gridBagConstraints);

        spSalidaHasta.setModel(new javax.swing.SpinnerDateModel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        pnlEntradaMarcacion1.add(spSalidaHasta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlEntrada1.add(pnlEntradaMarcacion1, gridBagConstraints);

        chkDiaSiguiente.setText("¿Día siguiente?");
        chkDiaSiguiente.setToolTipText("Este control sirve como referente para saber si la jornada del empleado pasa la medianoche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        pnlEntrada1.add(chkDiaSiguiente, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(pnlEntrada1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        jPanel1.add(jPanel2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!modificar){
            this.detalleJornada = new DetalleJornada();
        }        
        asignarValores();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!modificar){
            this.detalleJornada = null;
        }
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public DetalleJornada getDetalleJornada() {
        this.setVisible(true);
        return detalleJornada;
    }

    private boolean modificar = false;
    public void setDetalleJornada(DetalleJornada detalleJornada) {
        this.detalleJornada = detalleJornada;
        this.mostrar(this.detalleJornada);
        this.modificar = true;
        this.setVisible(true);
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgDetalleJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgDetalleJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgDetalleJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgDetalleJornada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgDetalleJornada dialog = new DlgDetalleJornada(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDiaSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlEntrada;
    private javax.swing.JPanel pnlEntrada1;
    private javax.swing.JPanel pnlEntradaMarcacion;
    private javax.swing.JPanel pnlEntradaMarcacion1;
    private javax.swing.JSpinner spEntrada;
    private javax.swing.JSpinner spEntradaDesde;
    private javax.swing.JSpinner spEntradaHasta;
    private javax.swing.JSpinner spEntradaTolerancia;
    private javax.swing.JSpinner spSalida;
    private javax.swing.JSpinner spSalidaDesde;
    private javax.swing.JSpinner spSalidaHasta;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        String patronHora = "HH:mm";
        FormularioUtil.modeloSpinnerFechaHora(spEntrada, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spEntradaTolerancia, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spEntradaDesde, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spEntradaHasta, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spSalida, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spSalidaDesde, patronHora);
        FormularioUtil.modeloSpinnerFechaHora(spSalidaHasta, patronHora);
//        detalleJornada = new DetalleJornada();
    }

    private void asignarValores() {
        this.detalleJornada.setEntrada((Date)spEntrada.getValue());
        this.detalleJornada.setEntradaDesde((Date)spEntradaDesde.getValue());
        this.detalleJornada.setEntradaTolerancia((Date)spEntradaTolerancia.getValue());
        this.detalleJornada.setEntradaHasta((Date)spEntradaHasta.getValue());
        //SALIDA
        this.detalleJornada.setSalida((Date)spSalida.getValue());
        this.detalleJornada.setSalidaDesde((Date)spSalidaDesde.getValue());
        this.detalleJornada.setSalidaHasta((Date)spSalidaHasta.getValue());
        this.detalleJornada.setSalidaDiaSiguiente(chkDiaSiguiente.isSelected());
    }

    private void mostrar(DetalleJornada detalle) {
        this.spEntrada.setValue(detalle.getEntrada());
        this.spEntradaDesde.setValue(detalle.getEntradaDesde());        
        this.spEntradaTolerancia.setValue(detalle.getEntradaTolerancia());
        this.spEntradaHasta.setValue(detalle.getEntradaHasta());
        //SALIDA
        this.spSalida.setValue(detalle.getSalida());
        this.spSalidaDesde.setValue(detalle.getSalidaDesde());        
        this.spSalidaHasta.setValue(detalle.getSalidaHasta());
        this.chkDiaSiguiente.setSelected(detalle.isSalidaDiaSiguiente());
    }
}
