/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.dialogos;

import controladores.JornadaControlador;
import controladores.TurnoControlador;
import entidades.DetalleJornada;
import entidades.Jornada;
import entidades.Turno;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.TreePath;
import org.jdesktop.swingx.renderer.IconValue;
import vistas.modelos.MTRJornada;

/**
 *
 * @author RyuujiMD
 */
public class DlgTurno extends javax.swing.JDialog {

    /**
     * Creates new form DlgImportarDNI
     *
     * @param padre
     * @param modal
     */
    private final JornadaControlador jc;
    private final TurnoControlador tc;

    public DlgTurno(JInternalFrame padre) {
        super(JOptionPane.getFrameForComponent(padre), true);
        jc = JornadaControlador.getInstance();
        tc = TurnoControlador.getInstance();
        initComponents();
        iniciar();

        this.setLocationRelativeTo(padre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        pnlJornada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trtblJornada = new org.jdesktop.swingx.JXTreeTable(new MTRJornada(jc.buscarTodos()));
        pnlDias = new javax.swing.JPanel();
        chkLunes = new javax.swing.JCheckBox();
        chkMartes = new javax.swing.JCheckBox();
        chkMiercoles = new javax.swing.JCheckBox();
        chkJueves = new javax.swing.JCheckBox();
        chkViernes = new javax.swing.JCheckBox();
        chkSabado = new javax.swing.JCheckBox();
        chkDomingo = new javax.swing.JCheckBox();
        pnlBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importar empleados");

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 7, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        pnlJornada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione la jornada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N
        pnlJornada.setLayout(new java.awt.GridBagLayout());

        trtblJornada.setRootVisible(false);
        trtblJornada.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        trtblJornada.setRowHeight(30);
        jScrollPane1.setViewportView(trtblJornada);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        pnlJornada.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        jPanel2.add(pnlJornada, gridBagConstraints);

        pnlDias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione los días laborales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N
        pnlDias.setLayout(new java.awt.GridLayout(0, 1));

        chkLunes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkLunes.setText("Lunes");
        pnlDias.add(chkLunes);

        chkMartes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkMartes.setText("Martes");
        pnlDias.add(chkMartes);

        chkMiercoles.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkMiercoles.setText("Miércoles");
        pnlDias.add(chkMiercoles);

        chkJueves.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkJueves.setText("Jueves");
        pnlDias.add(chkJueves);

        chkViernes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkViernes.setText("Viernes");
        pnlDias.add(chkViernes);

        chkSabado.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkSabado.setText("Sábado");
        pnlDias.add(chkSabado);

        chkDomingo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        chkDomingo.setText("Domingo");
        pnlDias.add(chkDomingo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        jPanel2.add(pnlDias, gridBagConstraints);

        pnlBotones.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnAgregar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar detalle");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAgregar);

        btnCancelar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(pnlBotones, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int fila = trtblJornada.getSelectedRow();
        TreePath treePath = trtblJornada.getPathForRow(fila);
        Object elemento = treePath.getLastPathComponent();
        Jornada jornada = null;
        if(elemento instanceof Jornada){
            jornada = ((Jornada)elemento);            
        }else if(elemento instanceof DetalleJornada){
            jornada = ((DetalleJornada)elemento).getJornada();
        }
        if(jornada != null){
            Turno turno = new Turno();
            turno.setJornada(jornada);
            turno.setLunes(chkLunes.isSelected());
            turno.setMartes(chkMartes.isSelected());
            turno.setMiercoles(chkMiercoles.isSelected());
            turno.setJueves(chkJueves.isSelected());
            turno.setViernes(chkViernes.isSelected());
            turno.setSabado(chkSabado.isSelected());
            turno.setDomingo(chkDomingo.isSelected());
            this.turnoSeleccionado = turno;
            this.dispose();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.turnoSeleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgImportarDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgImportarDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgImportarDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgImportarDNI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgImportarDNI dialog = new DlgImportarDNI(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkDomingo;
    private javax.swing.JCheckBox chkJueves;
    private javax.swing.JCheckBox chkLunes;
    private javax.swing.JCheckBox chkMartes;
    private javax.swing.JCheckBox chkMiercoles;
    private javax.swing.JCheckBox chkSabado;
    private javax.swing.JCheckBox chkViernes;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDias;
    private javax.swing.JPanel pnlJornada;
    private org.jdesktop.swingx.JXTreeTable trtblJornada;
    // End of variables declaration//GEN-END:variables
    private Turno turnoSeleccionado;
//    public List<String> obtenerDNI() {
//        this.setVisible(true);
//        return dnis;
//    }
//
//    private void leerCSV(String url) {
//        try {
//            CSVReader reader = new CSVReader(new FileReader(url));
//            String[] lineaSgte;
//            while ((lineaSgte = reader.readNext()) != null) {
//                dnis.add(lineaSgte[0]);
//            }
//            this.dispose();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(DlgTurno.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(DlgTurno.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    private MTRJornada modeloJornada;

    private void iniciar() {
        ImageIcon iconoJornada = new ImageIcon("iconos/icon_jornada.png");
        IconValue iv = new IconValue() {
            ImageIcon iconoJornada = new ImageIcon("iconos/icon_jornada.png");
            @Override
            public Icon getIcon(Object nodo) {
                if(nodo instanceof Jornada){
                    return iconoJornada;
                }else{
                    return null;
                }
            }
        };

        trtblJornada.setClosedIcon(iconoJornada);                        
        trtblJornada.setOpenIcon(iconoJornada);               
        trtblJornada.packAll();
    }
    
    public Turno getSeleccionado(){
        this.setVisible(true);
        return this.turnoSeleccionado;
    }
}
